export {
  getDifferenceViewOption,
  setDifferenceViewOption,
  getFavourites,
  addToFavourites,
  removeFromFavourites,
  getWatchlist,
  addEntryToWatchlist,
  removeEntryFromWatchlist,
  refreshEntryInWatchlist,
  getNotifications,
  addOrUpdateNotification,
  removeNotification,
  isValidNotificationInputState,
  getSupportedIndices,
  getTickerList,
  getSuffixForIndex,
  roundToDecimal,
  getAlertSoundList,
  notifyIfNeeded,
  playSound,
  showInformationMessage,
  watchlistEventEmitter,
  tickerEventEmitter,
} from './utils';
export { searchSymbol, fetchQuote } from './api';
export { ticker } from './ticker';
